### ISSUE TITLE
Other slug not working on windows

### ISSUE THREAD

**Issue by ShekhSaifuddin007** [SumonMSelim/llc04-ecommerce#1]
I saw your videos and creating a project the first url is working fine my route is `$router->controller('llc04-ecommerce', \App\Controllers\Frontend\HomeController::class);`, but when i want to go register page it shows me `Object not found!` how can i solve this..??

**Comment by SumonMSelim** [comment]
Can you please let me know what's your web server? Apache?

**Comment by ShekhSaifuddin007** [comment]
Ji vaiya, btw problem ta solve hoice, and thank for replying...

**Comment by ShekhSaifuddin007** [comment]
Vaiya apnara keno baire chole jan..? Amdr moto newcomer to valo valo mentor haraya feli...😢😢
